project:
  type: website

website:
  title: "home site"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - my-about.qmd
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



