project:
  type: website
  resources:
    - applets/calculator/**
    - applets/cindy-demo/**

website:
  title: "home site"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - my-about.qmd
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: applets/applets.qmd
        text: Applets

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



